language: ruby
addons:
  postgresql: "9.4"
bundler_args: --without production
before_script:
  - npm install -g bower
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake bower:install –force-latest
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
