# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  secret_key_base: 8a8cad25b24b1cab36b233e08a5b20aaca33b35fe42a5dd199fba27e90d72ea8da46bd9db37f0e6875c8cf58e52e073143a6b02254012e023d9a9f2ccd2687d5

test:
  secret_key_base: 9950b5b4a79af7ba0da9de0e1f1b13464260c6d8a4c67ff28e9b9ba31720cc71e6469d46290e741fd05434cb871a05dc6723fc151be7adc86bee0c7fec15bb9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
